project:
  type: book

lang: es

book:
  title: "Material del curso _Introducción a la programación con R_ (2024)"
  author: "Santiago Gualchi"
  date: "12/27/2024"
  chapters:
    - index.qmd
    - unos-y-ceros.qmd
    - hello-world.qmd
    - objetos.qmd
    - funciones.qmd
    - todo-es-un-objeto.qmd
    - todo-es-una-funcion.qmd
  downloads: [pdf, epub]

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-line-numbers: true
  epub:
    lang: es
    code-line-numbers: true
  pdf:
    documentclass: scrreprt

editor: visual

